### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by taylorbrooks** [kressaty/OpenVBX-Plugin-Call-Log#1]
Numbers aren't showing up in my call log and every call's status is marked 'Not Yet Dialed'.

I've tried troubleshooting, when I look in my Twilio logs, it shows the number and the status marked 'Completed.'

**Comment by tulipneo** [comment]
Hi 
Numbers dont show bcoz twilio upgraded its api or some thing.
go to plugin/callog folder and u will find call_log.php.u can update the bellow line

<td><?php echo format_phone($call->Caller);?></td>
<td><?php echo format_phone($call->Called);?></td>

to

<td><?php echo format_phone($call->From);?></td>
<td><?php echo format_phone($call->To);?></td>

Br
Tulip

**Comment by tulipneo** [comment]
Hi taylorbrooks,
Forgot to mention that for status of call...

replace the line 
 <td><?php echo status_text($call->Status);?></td>

with
<td><?php echo $call->status;?></td>

Cheers.
Tulip

**Comment by taylorbrooks** [comment]
Thanks, that fixed it!
